parent=keycloak
styles=css/styles.css
termsUrl=https://example.com/terms
termsApiUrl=http://general-dev-api.symc.net.th/terms-api/api/v1/public/terms-of-use
brandThemeApiUrl=http://general-dev-api.symc.net.th/terms-api/api/v1/public/brand-theme/settings
